// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.js";
import * as $1 from "./routes/api/LiberAD.js";
import * as $2 from "./routes/api/getSites.js";
import * as $3 from "./routes/api/liberad.mjs";
import * as $4 from "./routes/api/sites.js";
import * as $5 from "./routes/index.js";
import * as $6 from "./routes/start.js";
import * as $$0 from "./islands/CodeGen.js";
import * as $$1 from "./islands/LiberComp/GlobalStyle.js";
import * as $$2 from "./islands/LiberComp/IndexCenter.js";
import * as $$3 from "./islands/LiberComp/Link.js";
import * as $$4 from "./islands/Ref.js";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/api/LiberAD.ts": $1,
    "./routes/api/getSites.ts": $2,
    "./routes/api/liberad.mjs": $3,
    "./routes/api/sites.ts": $4,
    "./routes/index.tsx": $5,
    "./routes/start.tsx": $6,
  },
  islands: {
    "./islands/CodeGen.tsx": $$0,
    "./islands/LiberComp/GlobalStyle.tsx": $$1,
    "./islands/LiberComp/IndexCenter.tsx": $$2,
    "./islands/LiberComp/Link.tsx": $$3,
    "./islands/Ref.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
