// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/api/[name].tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/LiberComp/GlobalStyle.tsx";
import * as $$1 from "./islands/LiberComp/IndexCenter.tsx";
import * as $$2 from "./islands/LiberComp/Link.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/api/[name].tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/LiberComp/GlobalStyle.tsx": $$0,
    "./islands/LiberComp/IndexCenter.tsx": $$1,
    "./islands/LiberComp/Link.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
