// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/api/LiberAD.ts";
import * as $2 from "./routes/api/[name].tsx";
import * as $3 from "./routes/api/ad.ts";
import * as $4 from "./routes/api/liberad.mjs";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/LiberComp/GlobalStyle.tsx";
import * as $$1 from "./islands/LiberComp/IndexCenter.tsx";
import * as $$2 from "./islands/LiberComp/Link.tsx";
import * as $$3 from "./islands/Ref.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/api/LiberAD.ts": $1,
    "./routes/api/[name].tsx": $2,
    "./routes/api/ad.ts": $3,
    "./routes/api/liberad.mjs": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/LiberComp/GlobalStyle.tsx": $$0,
    "./islands/LiberComp/IndexCenter.tsx": $$1,
    "./islands/LiberComp/Link.tsx": $$2,
    "./islands/Ref.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
